/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 48
#define LARGE_STATE_COUNT 10
#define SYMBOL_COUNT 41
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_line_comment = 1,
  sym_block_comment = 2,
  sym__whitespace = 3,
  sym__char = 4,
  sym_lit_int = 5,
  anon_sym_DQUOTE = 6,
  sym_ident = 7,
  anon_sym_LBRACE = 8,
  anon_sym_RBRACE = 9,
  anon_sym_PLUS = 10,
  anon_sym_DASH = 11,
  anon_sym_STAR = 12,
  anon_sym_SLASH = 13,
  anon_sym_EQ = 14,
  anon_sym_BANG = 15,
  anon_sym_BANG_EQ = 16,
  anon_sym_LT = 17,
  anon_sym_LT_EQ = 18,
  anon_sym_GT = 19,
  anon_sym_GT_EQ = 20,
  anon_sym_CARET = 21,
  anon_sym_if = 22,
  anon_sym_if_else = 23,
  anon_sym_while = 24,
  anon_sym_break = 25,
  anon_sym_fn = 26,
  sym_source_file = 27,
  sym__sep = 28,
  sym_lit_str = 29,
  sym__lit = 30,
  sym_block = 31,
  sym__item = 32,
  sym_operator_function = 33,
  sym_keyword_function = 34,
  sym_function_call = 35,
  sym_function_def = 36,
  aux_sym_source_file_repeat1 = 37,
  aux_sym__sep_repeat1 = 38,
  aux_sym_lit_str_repeat1 = 39,
  aux_sym_block_repeat1 = 40,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_line_comment] = "line_comment",
  [sym_block_comment] = "block_comment",
  [sym__whitespace] = "_whitespace",
  [sym__char] = "_char",
  [sym_lit_int] = "lit_int",
  [anon_sym_DQUOTE] = "\"",
  [sym_ident] = "ident",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_EQ] = "=",
  [anon_sym_BANG] = "!",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT] = ">",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_CARET] = "^",
  [anon_sym_if] = "if",
  [anon_sym_if_else] = "if_else",
  [anon_sym_while] = "while",
  [anon_sym_break] = "break",
  [anon_sym_fn] = "fn",
  [sym_source_file] = "source_file",
  [sym__sep] = "_sep",
  [sym_lit_str] = "lit_str",
  [sym__lit] = "_lit",
  [sym_block] = "block",
  [sym__item] = "_item",
  [sym_operator_function] = "operator_function",
  [sym_keyword_function] = "keyword_function",
  [sym_function_call] = "function_call",
  [sym_function_def] = "function_def",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__sep_repeat1] = "_sep_repeat1",
  [aux_sym_lit_str_repeat1] = "lit_str_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_line_comment] = sym_line_comment,
  [sym_block_comment] = sym_block_comment,
  [sym__whitespace] = sym__whitespace,
  [sym__char] = sym__char,
  [sym_lit_int] = sym_lit_int,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_ident] = sym_ident,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_if_else] = anon_sym_if_else,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_break] = anon_sym_break,
  [anon_sym_fn] = anon_sym_fn,
  [sym_source_file] = sym_source_file,
  [sym__sep] = sym__sep,
  [sym_lit_str] = sym_lit_str,
  [sym__lit] = sym__lit,
  [sym_block] = sym_block,
  [sym__item] = sym__item,
  [sym_operator_function] = sym_operator_function,
  [sym_keyword_function] = sym_keyword_function,
  [sym_function_call] = sym_function_call,
  [sym_function_def] = sym_function_def,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__sep_repeat1] = aux_sym__sep_repeat1,
  [aux_sym_lit_str_repeat1] = aux_sym_lit_str_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__whitespace] = {
    .visible = false,
    .named = true,
  },
  [sym__char] = {
    .visible = false,
    .named = true,
  },
  [sym_lit_int] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_break] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__sep] = {
    .visible = false,
    .named = true,
  },
  [sym_lit_str] = {
    .visible = true,
    .named = true,
  },
  [sym__lit] = {
    .visible = false,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_operator_function] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_function] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_function_def] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__sep_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_lit_str_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_name = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 3},
    {field_name, 2},
  [2] =
    {field_name, 0},
  [3] =
    {field_body, 4},
    {field_name, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 8,
  [13] = 9,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 8,
  [29] = 29,
  [30] = 9,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
};

static const TSCharacterRange sym__whitespace_character_set_1[] = {
  {'\t', '\r'}, {' ', ' '}, {0x85, 0x85}, {0xa0, 0xa0}, {0x1680, 0x1680}, {0x2000, 0x200a}, {0x2028, 0x2029}, {0x202f, 0x202f},
  {0x205f, 0x205f}, {0x3000, 0x3000},
};

static const TSCharacterRange sym_ident_character_set_1[] = {
  {'#', '&'}, {'*', '+'}, {'-', '/'}, {'<', '>'}, {'A', 'Z'}, {'^', '_'}, {'a', 'z'}, {'|', '|'},
  {'~', '~'},
};

static const TSCharacterRange sym_ident_character_set_2[] = {
  {'#', '&'}, {'*', '+'}, {'-', '9'}, {'<', '>'}, {'A', 'Z'}, {'^', '_'}, {'a', 'z'}, {'|', '|'},
  {'~', '~'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      ADVANCE_MAP(
        '!', 52,
        '"', 21,
        '*', 45,
        '+', 41,
        '-', 43,
        '/', 47,
        '<', 55,
        '=', 50,
        '>', 58,
        '\\', 18,
        '^', 61,
        '{', 39,
        '}', 40,
      );
      if (set_contains(sym__whitespace_character_set_1, 10, lookahead)) ADVANCE(16);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 53,
        '"', 21,
        '*', 46,
        '+', 42,
        '-', 44,
        '/', 48,
        '<', 56,
        '=', 51,
        '>', 59,
        '^', 62,
        'b', 36,
        'i', 30,
        'w', 31,
        '{', 39,
        '}', 40,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (set_contains(sym__whitespace_character_set_1, 10, lookahead)) ADVANCE(16);
      if (('#' <= lookahead && lookahead <= '&') ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '~')) ADVANCE(38);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '!', 53,
        '"', 21,
        '*', 46,
        '+', 42,
        '-', 44,
        '/', 49,
        '<', 56,
        '=', 51,
        '>', 59,
        '^', 62,
        'b', 36,
        'i', 30,
        'w', 31,
        '{', 39,
        '}', 40,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (('#' <= lookahead && lookahead <= '&') ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '~')) ADVANCE(38);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '\\') ADVANCE(18);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(14);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(22);
      if (set_contains(sym__whitespace_character_set_1, 10, lookahead)) ADVANCE(16);
      if (set_contains(sym_ident_character_set_1, 9, lookahead)) ADVANCE(38);
      END_STATE();
    case 8:
      if (lookahead == 'n') ADVANCE(67);
      END_STATE();
    case 9:
      if (set_contains(sym_ident_character_set_1, 9, lookahead)) ADVANCE(38);
      END_STATE();
    case 10:
      if (eof) ADVANCE(11);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == 'f') ADVANCE(8);
      if (lookahead == '{') ADVANCE(39);
      if (lookahead == '}') ADVANCE(40);
      if (set_contains(sym__whitespace_character_set_1, 10, lookahead)) ADVANCE(16);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_line_comment);
      if (set_contains(sym_ident_character_set_2, 9, lookahead)) ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_block_comment);
      if (lookahead == '*') ADVANCE(5);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_block_comment);
      if (lookahead == '*') ADVANCE(23);
      if (set_contains(sym_ident_character_set_2, 9, lookahead)) ADVANCE(24);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym__whitespace);
      if (set_contains(sym__whitespace_character_set_1, 10, lookahead)) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym__char);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym__char);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(17);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_lit_int);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_lit_int);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      if (set_contains(sym_ident_character_set_2, 9, lookahead)) ADVANCE(38);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '*') ADVANCE(24);
      if (lookahead == '/') ADVANCE(12);
      if (set_contains(sym_ident_character_set_2, 9, lookahead)) ADVANCE(38);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '*') ADVANCE(23);
      if (lookahead == '/') ADVANCE(15);
      if (set_contains(sym_ident_character_set_2, 9, lookahead)) ADVANCE(24);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '*') ADVANCE(23);
      if (set_contains(sym_ident_character_set_2, 9, lookahead)) ADVANCE(24);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'a') ADVANCE(33);
      if (set_contains(sym_ident_character_set_2, 9, lookahead)) ADVANCE(38);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'e') ADVANCE(25);
      if (set_contains(sym_ident_character_set_2, 9, lookahead)) ADVANCE(38);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'e') ADVANCE(65);
      if (set_contains(sym_ident_character_set_2, 9, lookahead)) ADVANCE(38);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'e') ADVANCE(64);
      if (set_contains(sym_ident_character_set_2, 9, lookahead)) ADVANCE(38);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'e') ADVANCE(34);
      if (set_contains(sym_ident_character_set_2, 9, lookahead)) ADVANCE(38);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'f') ADVANCE(63);
      if (set_contains(sym_ident_character_set_2, 9, lookahead)) ADVANCE(38);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'h') ADVANCE(32);
      if (set_contains(sym_ident_character_set_2, 9, lookahead)) ADVANCE(38);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'i') ADVANCE(35);
      if (set_contains(sym_ident_character_set_2, 9, lookahead)) ADVANCE(38);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'k') ADVANCE(66);
      if (set_contains(sym_ident_character_set_2, 9, lookahead)) ADVANCE(38);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'l') ADVANCE(37);
      if (set_contains(sym_ident_character_set_2, 9, lookahead)) ADVANCE(38);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'l') ADVANCE(27);
      if (set_contains(sym_ident_character_set_2, 9, lookahead)) ADVANCE(38);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'r') ADVANCE(26);
      if (set_contains(sym_ident_character_set_2, 9, lookahead)) ADVANCE(38);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 's') ADVANCE(28);
      if (set_contains(sym_ident_character_set_2, 9, lookahead)) ADVANCE(38);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_ident);
      if (set_contains(sym_ident_character_set_2, 9, lookahead)) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_PLUS);
      if (set_contains(sym_ident_character_set_2, 9, lookahead)) ADVANCE(38);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      if (set_contains(sym_ident_character_set_2, 9, lookahead)) ADVANCE(38);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (set_contains(sym_ident_character_set_2, 9, lookahead)) ADVANCE(38);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(24);
      if (lookahead == '/') ADVANCE(12);
      if (set_contains(sym_ident_character_set_2, 9, lookahead)) ADVANCE(38);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (set_contains(sym_ident_character_set_2, 9, lookahead)) ADVANCE(38);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (set_contains(sym_ident_character_set_2, 9, lookahead)) ADVANCE(38);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(54);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(57);
      if (set_contains(sym_ident_character_set_2, 9, lookahead)) ADVANCE(38);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      if (set_contains(sym_ident_character_set_2, 9, lookahead)) ADVANCE(38);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(60);
      if (set_contains(sym_ident_character_set_2, 9, lookahead)) ADVANCE(38);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      if (set_contains(sym_ident_character_set_2, 9, lookahead)) ADVANCE(38);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_CARET);
      if (set_contains(sym_ident_character_set_2, 9, lookahead)) ADVANCE(38);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_if);
      if (lookahead == '_') ADVANCE(29);
      if (set_contains(sym_ident_character_set_2, 9, lookahead)) ADVANCE(38);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_if_else);
      if (set_contains(sym_ident_character_set_2, 9, lookahead)) ADVANCE(38);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_while);
      if (set_contains(sym_ident_character_set_2, 9, lookahead)) ADVANCE(38);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_break);
      if (set_contains(sym_ident_character_set_2, 9, lookahead)) ADVANCE(38);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 10},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 10},
  [11] = {.lex_state = 10},
  [12] = {.lex_state = 10},
  [13] = {.lex_state = 10},
  [14] = {.lex_state = 10},
  [15] = {.lex_state = 10},
  [16] = {.lex_state = 10},
  [17] = {.lex_state = 10},
  [18] = {.lex_state = 10},
  [19] = {.lex_state = 10},
  [20] = {.lex_state = 10},
  [21] = {.lex_state = 10},
  [22] = {.lex_state = 10},
  [23] = {.lex_state = 10},
  [24] = {.lex_state = 10},
  [25] = {.lex_state = 10},
  [26] = {.lex_state = 10},
  [27] = {.lex_state = 10},
  [28] = {.lex_state = 7},
  [29] = {.lex_state = 10},
  [30] = {.lex_state = 7},
  [31] = {.lex_state = 10},
  [32] = {.lex_state = 10},
  [33] = {.lex_state = 10},
  [34] = {.lex_state = 10},
  [35] = {.lex_state = 10},
  [36] = {.lex_state = 10},
  [37] = {.lex_state = 10},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 10},
  [40] = {.lex_state = 10},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 10},
  [44] = {.lex_state = 10},
  [45] = {.lex_state = 10},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 9},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__whitespace] = ACTIONS(1),
    [sym__char] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(46),
    [sym__sep] = STATE(39),
    [sym_function_def] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(11),
    [aux_sym__sep_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_line_comment] = ACTIONS(5),
    [sym_block_comment] = ACTIONS(5),
    [sym__whitespace] = ACTIONS(5),
    [anon_sym_fn] = ACTIONS(7),
  },
  [STATE(2)] = {
    [sym__sep] = STATE(3),
    [sym_lit_str] = STATE(14),
    [sym__lit] = STATE(14),
    [sym_block] = STATE(14),
    [sym__item] = STATE(14),
    [sym_operator_function] = STATE(33),
    [sym_keyword_function] = STATE(33),
    [sym_function_call] = STATE(14),
    [aux_sym__sep_repeat1] = STATE(9),
    [sym_line_comment] = ACTIONS(9),
    [sym_block_comment] = ACTIONS(9),
    [sym__whitespace] = ACTIONS(9),
    [sym_lit_int] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_ident] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(19),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(21),
    [anon_sym_SLASH] = ACTIONS(21),
    [anon_sym_EQ] = ACTIONS(21),
    [anon_sym_BANG] = ACTIONS(21),
    [anon_sym_BANG_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(21),
    [anon_sym_LT_EQ] = ACTIONS(21),
    [anon_sym_GT] = ACTIONS(21),
    [anon_sym_GT_EQ] = ACTIONS(21),
    [anon_sym_CARET] = ACTIONS(21),
    [anon_sym_if] = ACTIONS(25),
    [anon_sym_if_else] = ACTIONS(25),
    [anon_sym_while] = ACTIONS(25),
    [anon_sym_break] = ACTIONS(25),
  },
  [STATE(3)] = {
    [sym__sep] = STATE(45),
    [sym_lit_str] = STATE(17),
    [sym__lit] = STATE(17),
    [sym_block] = STATE(17),
    [sym__item] = STATE(17),
    [sym_operator_function] = STATE(33),
    [sym_keyword_function] = STATE(33),
    [sym_function_call] = STATE(17),
    [aux_sym__sep_repeat1] = STATE(13),
    [sym_line_comment] = ACTIONS(5),
    [sym_block_comment] = ACTIONS(5),
    [sym__whitespace] = ACTIONS(5),
    [sym_lit_int] = ACTIONS(27),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_ident] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(29),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(21),
    [anon_sym_SLASH] = ACTIONS(21),
    [anon_sym_EQ] = ACTIONS(21),
    [anon_sym_BANG] = ACTIONS(21),
    [anon_sym_BANG_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(21),
    [anon_sym_LT_EQ] = ACTIONS(21),
    [anon_sym_GT] = ACTIONS(21),
    [anon_sym_GT_EQ] = ACTIONS(21),
    [anon_sym_CARET] = ACTIONS(21),
    [anon_sym_if] = ACTIONS(25),
    [anon_sym_if_else] = ACTIONS(25),
    [anon_sym_while] = ACTIONS(25),
    [anon_sym_break] = ACTIONS(25),
  },
  [STATE(4)] = {
    [sym_lit_str] = STATE(35),
    [sym__lit] = STATE(35),
    [sym_block] = STATE(35),
    [sym__item] = STATE(35),
    [sym_operator_function] = STATE(33),
    [sym_keyword_function] = STATE(33),
    [sym_function_call] = STATE(35),
    [sym_lit_int] = ACTIONS(31),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_ident] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(33),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(21),
    [anon_sym_SLASH] = ACTIONS(21),
    [anon_sym_EQ] = ACTIONS(21),
    [anon_sym_BANG] = ACTIONS(21),
    [anon_sym_BANG_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(21),
    [anon_sym_LT_EQ] = ACTIONS(21),
    [anon_sym_GT] = ACTIONS(21),
    [anon_sym_GT_EQ] = ACTIONS(21),
    [anon_sym_CARET] = ACTIONS(21),
    [anon_sym_if] = ACTIONS(25),
    [anon_sym_if_else] = ACTIONS(25),
    [anon_sym_while] = ACTIONS(25),
    [anon_sym_break] = ACTIONS(25),
  },
  [STATE(5)] = {
    [sym_lit_str] = STATE(35),
    [sym__lit] = STATE(35),
    [sym_block] = STATE(35),
    [sym__item] = STATE(35),
    [sym_operator_function] = STATE(33),
    [sym_keyword_function] = STATE(33),
    [sym_function_call] = STATE(35),
    [sym_lit_int] = ACTIONS(31),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_ident] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(35),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(21),
    [anon_sym_SLASH] = ACTIONS(21),
    [anon_sym_EQ] = ACTIONS(21),
    [anon_sym_BANG] = ACTIONS(21),
    [anon_sym_BANG_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(21),
    [anon_sym_LT_EQ] = ACTIONS(21),
    [anon_sym_GT] = ACTIONS(21),
    [anon_sym_GT_EQ] = ACTIONS(21),
    [anon_sym_CARET] = ACTIONS(21),
    [anon_sym_if] = ACTIONS(25),
    [anon_sym_if_else] = ACTIONS(25),
    [anon_sym_while] = ACTIONS(25),
    [anon_sym_break] = ACTIONS(25),
  },
  [STATE(6)] = {
    [sym_lit_str] = STATE(35),
    [sym__lit] = STATE(35),
    [sym_block] = STATE(35),
    [sym__item] = STATE(35),
    [sym_operator_function] = STATE(33),
    [sym_keyword_function] = STATE(33),
    [sym_function_call] = STATE(35),
    [sym_lit_int] = ACTIONS(31),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_ident] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(37),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(21),
    [anon_sym_SLASH] = ACTIONS(21),
    [anon_sym_EQ] = ACTIONS(21),
    [anon_sym_BANG] = ACTIONS(21),
    [anon_sym_BANG_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(21),
    [anon_sym_LT_EQ] = ACTIONS(21),
    [anon_sym_GT] = ACTIONS(21),
    [anon_sym_GT_EQ] = ACTIONS(21),
    [anon_sym_CARET] = ACTIONS(21),
    [anon_sym_if] = ACTIONS(25),
    [anon_sym_if_else] = ACTIONS(25),
    [anon_sym_while] = ACTIONS(25),
    [anon_sym_break] = ACTIONS(25),
  },
  [STATE(7)] = {
    [sym_lit_str] = STATE(35),
    [sym__lit] = STATE(35),
    [sym_block] = STATE(35),
    [sym__item] = STATE(35),
    [sym_operator_function] = STATE(33),
    [sym_keyword_function] = STATE(33),
    [sym_function_call] = STATE(35),
    [sym_lit_int] = ACTIONS(31),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_ident] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(21),
    [anon_sym_SLASH] = ACTIONS(21),
    [anon_sym_EQ] = ACTIONS(21),
    [anon_sym_BANG] = ACTIONS(21),
    [anon_sym_BANG_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(21),
    [anon_sym_LT_EQ] = ACTIONS(21),
    [anon_sym_GT] = ACTIONS(21),
    [anon_sym_GT_EQ] = ACTIONS(21),
    [anon_sym_CARET] = ACTIONS(21),
    [anon_sym_if] = ACTIONS(25),
    [anon_sym_if_else] = ACTIONS(25),
    [anon_sym_while] = ACTIONS(25),
    [anon_sym_break] = ACTIONS(25),
  },
  [STATE(8)] = {
    [aux_sym__sep_repeat1] = STATE(8),
    [sym_line_comment] = ACTIONS(39),
    [sym_block_comment] = ACTIONS(39),
    [sym__whitespace] = ACTIONS(39),
    [sym_lit_int] = ACTIONS(42),
    [anon_sym_DQUOTE] = ACTIONS(44),
    [sym_ident] = ACTIONS(42),
    [anon_sym_LBRACE] = ACTIONS(44),
    [anon_sym_RBRACE] = ACTIONS(44),
    [anon_sym_PLUS] = ACTIONS(42),
    [anon_sym_DASH] = ACTIONS(42),
    [anon_sym_STAR] = ACTIONS(42),
    [anon_sym_SLASH] = ACTIONS(42),
    [anon_sym_EQ] = ACTIONS(42),
    [anon_sym_BANG] = ACTIONS(42),
    [anon_sym_BANG_EQ] = ACTIONS(44),
    [anon_sym_LT] = ACTIONS(42),
    [anon_sym_LT_EQ] = ACTIONS(42),
    [anon_sym_GT] = ACTIONS(42),
    [anon_sym_GT_EQ] = ACTIONS(42),
    [anon_sym_CARET] = ACTIONS(42),
    [anon_sym_if] = ACTIONS(42),
    [anon_sym_if_else] = ACTIONS(42),
    [anon_sym_while] = ACTIONS(42),
    [anon_sym_break] = ACTIONS(42),
  },
  [STATE(9)] = {
    [aux_sym__sep_repeat1] = STATE(8),
    [sym_line_comment] = ACTIONS(46),
    [sym_block_comment] = ACTIONS(46),
    [sym__whitespace] = ACTIONS(46),
    [sym_lit_int] = ACTIONS(48),
    [anon_sym_DQUOTE] = ACTIONS(50),
    [sym_ident] = ACTIONS(48),
    [anon_sym_LBRACE] = ACTIONS(50),
    [anon_sym_RBRACE] = ACTIONS(50),
    [anon_sym_PLUS] = ACTIONS(48),
    [anon_sym_DASH] = ACTIONS(48),
    [anon_sym_STAR] = ACTIONS(48),
    [anon_sym_SLASH] = ACTIONS(48),
    [anon_sym_EQ] = ACTIONS(48),
    [anon_sym_BANG] = ACTIONS(48),
    [anon_sym_BANG_EQ] = ACTIONS(50),
    [anon_sym_LT] = ACTIONS(48),
    [anon_sym_LT_EQ] = ACTIONS(48),
    [anon_sym_GT] = ACTIONS(48),
    [anon_sym_GT_EQ] = ACTIONS(48),
    [anon_sym_CARET] = ACTIONS(48),
    [anon_sym_if] = ACTIONS(48),
    [anon_sym_if_else] = ACTIONS(48),
    [anon_sym_while] = ACTIONS(48),
    [anon_sym_break] = ACTIONS(48),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(52), 1,
      ts_builtin_sym_end,
    ACTIONS(57), 1,
      anon_sym_fn,
    STATE(13), 1,
      aux_sym__sep_repeat1,
    STATE(43), 1,
      sym__sep,
    STATE(10), 2,
      sym_function_def,
      aux_sym_source_file_repeat1,
    ACTIONS(54), 3,
      sym_line_comment,
      sym_block_comment,
      sym__whitespace,
  [22] = 6,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(60), 1,
      ts_builtin_sym_end,
    STATE(13), 1,
      aux_sym__sep_repeat1,
    STATE(40), 1,
      sym__sep,
    STATE(10), 2,
      sym_function_def,
      aux_sym_source_file_repeat1,
    ACTIONS(5), 3,
      sym_line_comment,
      sym_block_comment,
      sym__whitespace,
  [44] = 3,
    STATE(12), 1,
      aux_sym__sep_repeat1,
    ACTIONS(62), 3,
      sym_line_comment,
      sym_block_comment,
      sym__whitespace,
    ACTIONS(44), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_fn,
  [59] = 3,
    STATE(12), 1,
      aux_sym__sep_repeat1,
    ACTIONS(65), 3,
      sym_line_comment,
      sym_block_comment,
      sym__whitespace,
    ACTIONS(50), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_fn,
  [74] = 5,
    ACTIONS(29), 1,
      anon_sym_RBRACE,
    STATE(4), 1,
      sym__sep,
    STATE(9), 1,
      aux_sym__sep_repeat1,
    STATE(16), 1,
      aux_sym_block_repeat1,
    ACTIONS(9), 3,
      sym_line_comment,
      sym_block_comment,
      sym__whitespace,
  [92] = 5,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    STATE(13), 1,
      aux_sym__sep_repeat1,
    STATE(29), 1,
      sym_block,
    STATE(44), 1,
      sym__sep,
    ACTIONS(5), 3,
      sym_line_comment,
      sym_block_comment,
      sym__whitespace,
  [110] = 5,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    STATE(5), 1,
      sym__sep,
    STATE(9), 1,
      aux_sym__sep_repeat1,
    STATE(19), 1,
      aux_sym_block_repeat1,
    ACTIONS(9), 3,
      sym_line_comment,
      sym_block_comment,
      sym__whitespace,
  [128] = 5,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    STATE(5), 1,
      sym__sep,
    STATE(9), 1,
      aux_sym__sep_repeat1,
    STATE(18), 1,
      aux_sym_block_repeat1,
    ACTIONS(9), 3,
      sym_line_comment,
      sym_block_comment,
      sym__whitespace,
  [146] = 5,
    ACTIONS(35), 1,
      anon_sym_RBRACE,
    STATE(6), 1,
      sym__sep,
    STATE(9), 1,
      aux_sym__sep_repeat1,
    STATE(19), 1,
      aux_sym_block_repeat1,
    ACTIONS(9), 3,
      sym_line_comment,
      sym_block_comment,
      sym__whitespace,
  [164] = 5,
    ACTIONS(70), 1,
      anon_sym_RBRACE,
    STATE(7), 1,
      sym__sep,
    STATE(9), 1,
      aux_sym__sep_repeat1,
    STATE(19), 1,
      aux_sym_block_repeat1,
    ACTIONS(67), 3,
      sym_line_comment,
      sym_block_comment,
      sym__whitespace,
  [182] = 1,
    ACTIONS(72), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      sym_block_comment,
      sym__whitespace,
      anon_sym_RBRACE,
      anon_sym_fn,
  [191] = 1,
    ACTIONS(74), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      sym_block_comment,
      sym__whitespace,
      anon_sym_RBRACE,
      anon_sym_fn,
  [200] = 1,
    ACTIONS(76), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      sym_block_comment,
      sym__whitespace,
      anon_sym_RBRACE,
      anon_sym_fn,
  [209] = 1,
    ACTIONS(78), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      sym_block_comment,
      sym__whitespace,
      anon_sym_RBRACE,
      anon_sym_fn,
  [218] = 1,
    ACTIONS(80), 6,
      ts_builtin_sym_end,
      sym_line_comment,
      sym_block_comment,
      sym__whitespace,
      anon_sym_RBRACE,
      anon_sym_fn,
  [227] = 1,
    ACTIONS(82), 5,
      ts_builtin_sym_end,
      sym_line_comment,
      sym_block_comment,
      sym__whitespace,
      anon_sym_fn,
  [235] = 3,
    STATE(30), 1,
      aux_sym__sep_repeat1,
    STATE(47), 1,
      sym__sep,
    ACTIONS(84), 3,
      sym_line_comment,
      sym_block_comment,
      sym__whitespace,
  [247] = 1,
    ACTIONS(52), 5,
      ts_builtin_sym_end,
      sym_line_comment,
      sym_block_comment,
      sym__whitespace,
      anon_sym_fn,
  [255] = 3,
    ACTIONS(42), 1,
      sym_ident,
    STATE(28), 1,
      aux_sym__sep_repeat1,
    ACTIONS(86), 3,
      sym_line_comment,
      sym_block_comment,
      sym__whitespace,
  [267] = 1,
    ACTIONS(89), 5,
      ts_builtin_sym_end,
      sym_line_comment,
      sym_block_comment,
      sym__whitespace,
      anon_sym_fn,
  [275] = 3,
    ACTIONS(48), 1,
      sym_ident,
    STATE(28), 1,
      aux_sym__sep_repeat1,
    ACTIONS(91), 3,
      sym_line_comment,
      sym_block_comment,
      sym__whitespace,
  [287] = 1,
    ACTIONS(93), 4,
      sym_line_comment,
      sym_block_comment,
      sym__whitespace,
      anon_sym_RBRACE,
  [294] = 1,
    ACTIONS(95), 4,
      sym_line_comment,
      sym_block_comment,
      sym__whitespace,
      anon_sym_RBRACE,
  [301] = 1,
    ACTIONS(97), 4,
      sym_line_comment,
      sym_block_comment,
      sym__whitespace,
      anon_sym_RBRACE,
  [308] = 1,
    ACTIONS(99), 4,
      sym_line_comment,
      sym_block_comment,
      sym__whitespace,
      anon_sym_RBRACE,
  [315] = 1,
    ACTIONS(70), 4,
      sym_line_comment,
      sym_block_comment,
      sym__whitespace,
      anon_sym_RBRACE,
  [322] = 1,
    ACTIONS(101), 4,
      sym_line_comment,
      sym_block_comment,
      sym__whitespace,
      anon_sym_RBRACE,
  [329] = 1,
    ACTIONS(103), 4,
      sym_line_comment,
      sym_block_comment,
      sym__whitespace,
      anon_sym_RBRACE,
  [336] = 3,
    ACTIONS(105), 1,
      sym__char,
    ACTIONS(107), 1,
      anon_sym_DQUOTE,
    STATE(42), 1,
      aux_sym_lit_str_repeat1,
  [346] = 3,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(60), 1,
      ts_builtin_sym_end,
    STATE(27), 1,
      sym_function_def,
  [356] = 3,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(109), 1,
      ts_builtin_sym_end,
    STATE(27), 1,
      sym_function_def,
  [366] = 3,
    ACTIONS(111), 1,
      sym__char,
    ACTIONS(113), 1,
      anon_sym_DQUOTE,
    STATE(38), 1,
      aux_sym_lit_str_repeat1,
  [376] = 3,
    ACTIONS(115), 1,
      sym__char,
    ACTIONS(118), 1,
      anon_sym_DQUOTE,
    STATE(42), 1,
      aux_sym_lit_str_repeat1,
  [386] = 2,
    ACTIONS(7), 1,
      anon_sym_fn,
    STATE(27), 1,
      sym_function_def,
  [393] = 2,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    STATE(25), 1,
      sym_block,
  [400] = 1,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
  [404] = 1,
    ACTIONS(120), 1,
      ts_builtin_sym_end,
  [408] = 1,
    ACTIONS(122), 1,
      sym_ident,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(10)] = 0,
  [SMALL_STATE(11)] = 22,
  [SMALL_STATE(12)] = 44,
  [SMALL_STATE(13)] = 59,
  [SMALL_STATE(14)] = 74,
  [SMALL_STATE(15)] = 92,
  [SMALL_STATE(16)] = 110,
  [SMALL_STATE(17)] = 128,
  [SMALL_STATE(18)] = 146,
  [SMALL_STATE(19)] = 164,
  [SMALL_STATE(20)] = 182,
  [SMALL_STATE(21)] = 191,
  [SMALL_STATE(22)] = 200,
  [SMALL_STATE(23)] = 209,
  [SMALL_STATE(24)] = 218,
  [SMALL_STATE(25)] = 227,
  [SMALL_STATE(26)] = 235,
  [SMALL_STATE(27)] = 247,
  [SMALL_STATE(28)] = 255,
  [SMALL_STATE(29)] = 267,
  [SMALL_STATE(30)] = 275,
  [SMALL_STATE(31)] = 287,
  [SMALL_STATE(32)] = 294,
  [SMALL_STATE(33)] = 301,
  [SMALL_STATE(34)] = 308,
  [SMALL_STATE(35)] = 315,
  [SMALL_STATE(36)] = 322,
  [SMALL_STATE(37)] = 329,
  [SMALL_STATE(38)] = 336,
  [SMALL_STATE(39)] = 346,
  [SMALL_STATE(40)] = 356,
  [SMALL_STATE(41)] = 366,
  [SMALL_STATE(42)] = 376,
  [SMALL_STATE(43)] = 386,
  [SMALL_STATE(44)] = 393,
  [SMALL_STATE(45)] = 400,
  [SMALL_STATE(46)] = 404,
  [SMALL_STATE(47)] = 408,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__sep_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [42] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__sep_repeat1, 2, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__sep_repeat1, 2, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__sep, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sep, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__sep_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 6, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 5, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_def, 5, 0, 3),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__sep_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_def, 4, 0, 1),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lit_str, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lit_str, 3, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator_function, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 1, 0, 2),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword_function, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_lit_str_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_lit_str_repeat1, 2, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_sticker(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "sticker",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
